### ISSUE TITLE
 ret = input.log_softmax(dim) RuntimeError: cuda runtime error (77) : an illegal memory access was encountered 

### ISSUE THREAD

**Issue by xdsonglinliu** [junfu1115/DANet#71]
the environment configure:
CUDA10.0
VS2017
pytorch: 1.0.0
python:3.7
Win10
Anaconda3
torch_encoding-0.4.5-py3.7

when i run python,
`CUDA_VISIBLE_DEVICES=0 python train_singlegpu.py --dataset cityscapes --model  danet --backbone resnet101 --checkname danet101  --base-size 512 --crop-size 384 --epochs 240 --batch-size 6 --lr 0.003 --workers 1 --multi-grid --multi-dilation 4 8 16`

I have change the code to use one GPU.
But it could appeare below errors.
`Using poly LR Scheduler!
2019-06-03 23:32:30: Using poly LR Scheduler!
2019-06-03 23:32:30: ['Starting Epoch:', '0']
2019-06-03 23:32:30: ['Total Epoches:', '240']
  0%|          | 0/2975 [00:00<?, ?it/s]
  warnings.warn('Error checking compiler version for {}: {}'.format(compiler, error))
2019-06-03 23:32:32:
=>Epoches 0, learning rate = 0.0030,                 previous best = 0.0000
C:\Users\MSIK\Anaconda3\lib\site-packages\torch\nn\functional.py:2351: UserWarning: nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.
  warnings.warn("nn.functional.upsample is deprecated. Use nn.functional.interpolate instead.")
THCudaCheck FAIL file=C:/a/w/1/s/tmp_conda_3.7_061434/conda/conda-bld/pytorch_1544163540495/work/aten/src/ATen/native/cuda/SoftMax.cu line=545 error=77 : an illegal memory access was encountered
Traceback (most recent call last):
  File "train_singlegpu.py", line 204, in <module>
    trainer.training(epoch)
  File "train_singlegpu.py", line 129, in training
    loss = self.criterion(outputs, target)
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\encoding\nn\customize.py", line 105, in forward
    loss2 = super(SegmentationMultiLosses, self).forward(pred2, target)
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\torch\nn\modules\loss.py", line 904, in forward
    ignore_index=self.ignore_index, reduction=self.reduction)
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1970, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "C:\Users\MSIK\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1295, in log_softmax
    ret = input.log_softmax(dim)
RuntimeError: cuda runtime error (77) : an illegal memory access was encountered at C:/a/w/1/s/tmp_conda_3.7_061434/conda/conda-bld/pytorch_1544163540495/work/aten/src/ATen/native/cuda/SoftMax.cu:545
`
How I can solve this problem? Anyone can help me?
Thanks a lot!

**Comment by xdsonglinliu** [comment]
I have solved this problem.

**Comment by tjulyz** [comment]
@xdsonglinliu How do you solve this problem? I meet the similar one. Thank you!

**Comment by xdsonglinliu** [comment]
@tjulyz https://blog.csdn.net/m0_37759119/article/details/90730276
